databases:
  - name: notemind-db
    plan: free

services:
  - type: web
    name: notemind-api
    env: docker
    region: oregon
    plan: free
    dockerContext: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: STORAGE_BACKEND
        value: local
      - key: LOCAL_UPLOAD_DIR
        value: uploads
      - key: POSTGRES_URL
        fromDatabase:
          name: notemind-db
          property: connectionString
      - key: MONGO_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
